AllCops:
  Excludes:
    - bin/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
